Repository jupytercalpoly/jupyterlab-tabular-data-editor, pull requests merged in 2020-08, with the labels that each got.

#151 Selection UX for insert below, insert right, move row/column
  src/handler.ts
  src/widget.ts
Labels: design, enhancement

#150 Repo updates (07/27/20 - 07/31/20)
  MODEL_CHANGES.md
  PROGRESS.md
  README.md
Labels: documentation

#155 0.3.1
  package.json
  src/handler.ts
  src/widget.ts
Labels: publish

#159 Litestore refactor
  README.md
  src/litestore.ts
  src/model.ts
  src/searchprovider.ts
  src/widget.ts
Labels: enhancement

#161 Right-click selection fixes
  src/handler.ts
Labels: design

#163 Publish 0.4.0
  README.md
  demo/customer-recipes.csv
  src/handler.ts
  src/litestore.ts
  src/model.ts
  src/searchprovider.ts
  src/widget.ts
Labels: publish

#164 Shadow/line fixes when moving + handler.ts refactoring
  src/handler.ts
  src/selection.ts
Labels: bug, design, refactoring

#170 Reduced column header and row height. Scrollbar size change
  src/widget.ts
  style/index.css
Labels: design

#143 Alternative model
  package.json
  src/handler.ts
  src/index.ts
  src/litestore.ts
  src/model.ts
  src/newmodel.ts
  src/searchprovider.ts
  src/serialize.ts
  src/widget.ts
  test/model.spec.ts
  test/newmodel.spec.ts
Labels: enhancement, refactoring

#169 Create a new csv file from launcher
  package.json
  src/index.ts
Labels: enhancement

#172 Selection UX (Insert Below/Right/Moving with Undo/Redo)
  src/handler.ts
  src/newmodel.ts
  src/widget.ts
Labels: design

#173 Refactoring of the new model.
  src/index.ts
  src/newmodel.ts
  src/widget.ts
  test/newmodel.spec.ts
Labels: refactoring

#178 Save keybinding
  src/index.ts
Labels: enhancement

#179 Repo updates (08/03/20 - 08/07/20)
  MODEL_CHANGES.md
  PROGRESS.md
  README.md
Labels: documentation

#180 0.5.0
  MODEL_CHANGES.md
  PROGRESS.md
  README.md
  package.json
  src/handler.ts
  src/headercelleditor.ts
  src/index.ts
  src/litestore.ts
  src/model.ts
  src/newmodel.ts
  src/searchprovider.ts
  src/selection.ts
  src/serialize.ts
  src/widget.ts
  style/index.css
  test/model.spec.ts
  test/newmodel.spec.ts
Labels: publish

#181 Unsaved changes dialog
  src/dialog.ts
  src/newmodel.ts
  src/widget.ts
Labels: design, enhancement

#182 Refactor moveRows and moveColumns
  src/handler.ts
  src/newmodel.ts
Labels: refactoring

#183 Refactor and code cleanup in widget.ts around updateLitestore and updateModel.
  src/index.ts
  src/newmodel.ts
  src/widget.ts
Labels: refactoring

#184 Scroll and select the current match when searching
  src/searchprovider.ts
  src/widget.ts
Labels: design

#189 Paste bug fix/cut cells refactor
  src/newmodel.ts
  src/widget.ts
Labels: bug, refactoring

#190 0.5.1
  README.md
  package.json
  src/dialog.ts
  src/handler.ts
  src/index.ts
  src/newmodel.ts
  src/searchprovider.ts
  src/selection.ts
  src/widget.ts
Labels: publish

#191 Multi insert/remove for rows/columns
  README.md
  src/index.ts
  src/widget.ts
Labels: enhancement

#192 WCAG AAA approved search match colors
  src/index.ts
Labels: design

#197 Inserting/removing column bug fixes + refactor
  src/handler.ts
  src/newmodel.ts
  src/searchservice.ts
  src/widget.ts
  test/newmodel.spec.ts
Labels: bug, refactoring

#202 DataGrid extended to handle more flexible ui changes. Ghost rows and columns revamped.
  package.json
  src/grid.ts
  src/index.ts
  src/widget.ts
Labels: refactoring

#205 Console error when searching for a match
  src/handler.ts
  src/headercelleditor.ts
  src/searchservice.ts
  src/widget.ts
Labels: bug

#206 Serialization fix for data sets larger than 500 rows.
  package.json
  src/newmodel.ts
Labels: bug

#188 Different cell editors for the body region
  package.json
  src/newmodel.ts
  src/widget.ts
  style/index.css
Labels: design, enhancement

#209 0.6.0
  README.md
  package.json
  src/drag.ts
  src/grid.ts
  src/handler.ts
  src/headercelleditor.ts
  src/index.ts
  src/newmodel.ts
  src/searchservice.ts
  src/selectionmodel.ts
  src/widget.ts
  style/index.css
  test/newmodel.spec.ts
Labels: publish

#217 Text alignment with data detection
  src/newmodel.ts
  src/widget.ts
Labels: design

#218 Pointer cursor for ghost row/column
  src/handler.ts
Labels: design

#219 Modified icon painting setup to work with absolute positioning rather than relative positioning.
  src/grid.ts
  src/index.ts
Labels: design, refactoring

#220 Ghost row/column only for left clicks
  src/handler.ts
  src/widget.ts
Labels: bug

#221 Repo Updates - 08/10 - 08/14
  PROGRESS.md
Labels: documentation

#224 Styling for data detection icons
  src/grid.ts
  src/index.ts
Labels: design

#226 Fix launcher
  package.json
Labels: bug

#228 Replace all bug fix.
  package.json
  src/newmodel.ts
  src/searchprovider.ts
Labels: bug

#229 Test fix
  jest.config.js
  test/data.ts
  test/newmodel.spec.ts
  testutils/jest-style-mock.js
Labels: testing

#231 Makes the text "Column 1" appear on the column header when launching a csv file.
  src/widget.ts
Labels: enhancement

#233 Added more tests for the EditorModel + refactor
  test/newmodel.spec.ts
Labels: testing

#232 Selection not updating with replace bug fix.
  src/searchprovider.ts
Labels: bug

#242 Remove coverage folder from repo
  README.md
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov-report/src/_helper.ts.html
  coverage/lcov-report/src/index.html
  coverage/lcov-report/src/litestore.ts.html
  coverage/lcov-report/src/model.ts.html
  coverage/lcov-report/testutils/index.html
  coverage/lcov-report/testutils/jest-file-mock.js.html
  coverage/lcov.info
Labels: testing

#245 Removes unecessary code.
  src/handler.ts
  src/newmodel.ts
  src/widget.ts
Labels: refactoring

#247 0.7.0
  PROGRESS.md
  README.md
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov-report/src/_helper.ts.html
  coverage/lcov-report/src/index.html
  coverage/lcov-report/src/litestore.ts.html
  coverage/lcov-report/src/model.ts.html
  coverage/lcov-report/testutils/index.html
  coverage/lcov-report/testutils/jest-file-mock.js.html
  coverage/lcov.info
  jest.config.js
  package.json
  src/drag.ts
  src/grid.ts
  src/handler.ts
  src/headercelleditor.ts
  src/index.ts
  src/newmodel.ts
  src/searchprovider.ts
  src/selectionmodel.ts
  src/svg.d.ts
  src/widget.ts
  style/icons/calendar.svg
  style/icons/checkbox.svg
  style/icons/number.svg
  style/icons/string.svg
  test/data.ts
  test/newmodel.spec.ts
  testutils/jest-style-mock.js
Labels: publish

#249 Ghost row/columns bug fixes
  src/handler.ts
  src/index.ts
Labels: bug

#248 Added new files to the demo folder
  demo/customer-recipes.ipynb
  demo/survey-data(cleaned).csv
  demo/survey-data.ipynb
Labels: documentation

#265 Updated binder dependencies and workspace
  binder/requirements.txt
  binder/workspace.json
Labels: documentation

#266 Code cleanup primarily in handler.ts
  src/drag.ts
  src/grid.ts
  src/handler.ts
Labels: refactoring

#269 Code cleanup in handler.ts
  src/handler.ts
Labels: refactoring

#272 Right-click column header results in move shadow
  src/handler.ts
Labels: bug

#270 Fixes bug with search and replace when using data types.
  src/searchservice.ts
Labels: bug

#274 Datagrid Styling
  src/index.ts
  src/widget.ts
  style/index.css
Labels: design

#276 0.7.3
  package.json
  src/index.ts
  src/widget.ts
  style/index.css
Labels: publish

#282 Created a selectCell method in the PaintedGrid
  src/grid.ts
  src/mousehandler.ts
  src/searchprovider.ts
  src/widget.ts
Labels: refactoring

#284 Draw icon refactor
  src/grid.ts
Labels: refactoring

#288 Removed serializer and old model files
  src/grid.ts
  src/keyhandler.ts
  src/model.ts
  src/mousehandler.ts
  src/newmodel.ts
  src/selectionmodel.ts
  src/serialize.ts
  src/widget.ts
Labels: refactoring

#287 Added comments, esp to _invertMaps.
  src/model.ts
Labels: documentation

#290 Final repo updates for the summer
  PROGRESS.md
Labels: documentation

#291 0.7.4
  PROGRESS.md
  package.json
  src/drag.ts
  src/grid.ts
  src/keyhandler.ts
  src/model.ts
  src/mousehandler.ts
  src/newmodel.ts
  src/searchprovider.ts
  src/selectionmodel.ts
  src/serialize.ts
  src/widget.ts
Labels: publish

#293 0.7.5
  README.md
  package.json
  src/drag.ts
Labels: publish
