Repository jupytercalpoly/jupyterlab-tabular-data-editor, pull requests merged in 2020-07, with the labels that each got.

#25 Edit cells
  package.json
  src/editor.ts
  src/grid.ts
  src/model.ts
  src/widget.ts
Labels: enhancement

#30 Configured extension to get it's csvviewer objects from the node pack…
  package.json
  src/index.ts
  src/model.ts
  src/widget.ts
Labels: enhancement

#31 Edit cells
  src/widget.ts
  style/index.css
Labels: bug

#37 Repo updates
  PRESS_RELEASE.md
  PROGRESS.md
  README.md
Labels: documentation

#38 Design: Journey Maps and Editing cell prototype gif
  .DS_Store
  design/.DS_Store
  design/Journey-Maps/.DS_Store
  design/Journey-Maps/Addison-Journey-Map.png
  design/Journey-Maps/Hayden-Journey-Map.png
  design/Journey-Maps/Sam-Journey-Map.png
  design/gifs/.DS_Store
  design/gifs/edit-cell.gif
Labels: design

#41 Added UI/UX for User Story Issue Template
  .github/ISSUE_TEMPLATE/ui-ux-for-user-story.md
Labels: documentation

#46 Design: Removed alternating row colors and centered grid columns/rows
  design/gifs/edit-cell copy.gif
  src/index.ts
  style/index.css
Labels: design

#48 Delete columns
  src/model.ts
  src/widget.ts
Labels: bug

#52 Design: Added gifs of prototypes
  .DS_Store
  design/.DS_Store
  design/gifs/.DS_Store
  design/gifs/edit-cell copy.gif
  design/gifs/edit-cell.gif
  design/gifs/filter-sort.gif
  design/gifs/insert-delete.gif
  design/gifs/moving-data.gif
Labels: design

#55 Updated UI/UX for User Story Issue template
  .github/ISSUE_TEMPLATE/ui-ux-for-user-story.md
Labels: design

#49 Alphabetic column header
  src/_helper.ts
  src/model.ts
  src/widget.ts
Labels: enhancement

#44 Repo Updates - Week 07/06/20 - 07/10/20
  PROGRESS.md
  README.md
Labels: documentation

#59 Jest Setup
  .DS_Store
  .eslintignore
  .eslintrc.js
  .gitignore
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov.info
  jest.config.js
  package.json
  src/index.ts
  src/widget.ts
  test/model.spec.ts
  tsconfig.eslint.json
  tsconfig.json
Labels: enhancement

#61 Jest reconfig
  .eslintignore
  babel.config.js
  jest.config.js
  package.json
  test/model.spec.ts
  testutils/jest-file-mock.js
  testutils/jest-setup-files.js
  tsconfig.json
  tsconfig.test.json
Labels: bug

#65 Github workflow for testing
  .github/workflows/testing.yml
Labels: enhancement

#66 Toolbar icons added and styling changes
  .eslintrc.js
  .gitignore
  design/.DS_Store
  design/Journey-Maps/.DS_Store
  design/gifs/.DS_Store
  design/gifs/edit-cell.gif
  src/toolbar.ts
  src/widget.ts
  style/index.css
Labels: enhancement

#67 Additional tests for model functions
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/index.html
  coverage/lcov.info
  src/index.ts
  src/model.ts
  src/widget.ts
  test/model.spec.ts
Labels: enhancement

#78 Litestore implementation with undo/redo for basic cell editing functions
  package.json
  src/_helper.ts
  src/index.ts
  src/litestore.ts
  src/model.ts
  src/widget.ts
  test/model.spec.ts
Labels: enhancement

#81 Test reorganization/update coverage
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/index.html
  coverage/lcov.info
  test/model.spec.ts
Labels: documentation

#58 Repo updates
  PROGRESS.md
  README.md
Labels: documentation

#83 Search/replace functionality + working theme manager
  package.json
  src/index.ts
  src/searchprovider.ts
  src/widget.ts
Labels: enhancement

#92 Model.ts Changes
  src/model.ts
  test/model.spec.ts
Labels: enhancement, refactoring, testing

#95 Cell selection for undo/redo/searching
  src/handler.ts
  src/model.ts
  src/searchprovider.ts
  src/widget.ts
Labels: enhancement

#96 Dark theme and moving shadow styling changes + toolbar button signals
  src/index.ts
  src/toolbar.ts
  src/widget.ts
  style/index.css
Labels: design, enhancement

#107 Toolbar Actions (Undo, Redo, Cut, Copy)
  src/index.ts
  src/toolbar.ts
  src/widget.ts
Labels: enhancement

#103 Progress Updates (07/20/20 - 07/24/20)
  PROGRESS.md
Labels: documentation

#110 Toolbar commands linked
  src/index.ts
  src/model.ts
  src/widget.ts
  test/model.spec.ts
Labels: enhancement

#116 Algorithm improvement for operations on columns
  src/model.ts
Labels: enhancement

#118 Save command + undo/redo for cut/copy/paste
  src/index.ts
  src/model.ts
  src/toolbar.ts
  src/widget.ts
Labels: enhancement

#119 Eslint fixes and code cleanup
  src/handler.ts
  src/index.ts
  src/model.ts
  src/selection.ts
  src/widget.ts
Labels: refactoring

#121 Reorganized the context menu and added separators
  src/index.ts
Labels: design

#122 Replace all undo/redo
  src/index.ts
  src/model.ts
  src/searchprovider.ts
  src/widget.ts
Labels: bug

#124 Setup binder link
  README.md
  binder/customer-recipes.csv
  binder/postBuild
  binder/requirements.txt
  binder/workspace.json
Labels: documentation, enhancement

#125 Updated binder link to latest commit
  README.md
Labels: documentation

#127 New context menus added for different regions of the DataGrid
  package.json
  src/handler.ts
  src/index.ts
  src/model.ts
  src/selection.ts
  src/widget.ts
  style/index.css
Labels: enhancement

#136 Grab cursor for row/columns headers appears based on current selection
  src/handler.ts
Labels: bug, design

#139 0.2.0 publish
  README.md
  package.json
Labels: publish

#140 GridSearchService refactor
  README.md
  package.json
  src/searchprovider.ts
  src/searchservice.ts
  src/widget.ts
Labels: refactoring

#141 Building multiple context menus refactor
  src/index.ts
Labels: refactoring

#144 Clear contents functionality
  src/handler.ts
  src/index.ts
  src/model.ts
  src/widget.ts
  test/model.spec.ts
Labels: enhancement

#145 Color changes to cell selection, cell highlight border, and dark theme column header
  src/index.ts
  style/index.css
Labels: design

#146 0.3.0
  package.json
  src/handler.ts
  src/index.ts
  src/model.ts
  src/searchprovider.ts
  src/searchservice.ts
  src/widget.ts
  style/index.css
  test/model.spec.ts
Labels: publish
